### ISSUE TITLE
Error in build pipeline

### ISSUE THREAD

**Issue by bnordg** [CitrusAndriessen/tfs-mail-sendgrid#3]
Hi!
I'm getting an error on this task.. - appeared today.

```
Log: 
##[section]Starting: SendGrid 
==============================================================================
Task         : SendGrid
Description  : Build/Release task for sending mails (including ability for sending attachments) via SendGrid
Version      : 1.2.1
Author       : Jean-Pierre Broeders
Help         : Replace with markdown to show in help
==============================================================================
##[error]Unhandled: Cannot read property 'replace' of undefined
##[section]Finishing: SendGrid 

```

**Comment by jpbroeders** [comment]
Hi @bnordg,

Thanks for reporting the problem.
Can you please answer the following questions:

- On what kind of OS this build/release task is running?
- What did you put in the "To" and "Cc" fields?
- Was there a part "Mail Settings" in the output log? How does it look like?

I think the issue is in the Cc field, which is probably empty in your case!?
The migration to "azure-pipelines-task-lib" resulted in an undefined value if a field is empty, but on our Linux and Win agents I have no problem with the undefined value.

Thanks!

**Comment by bnordg** [comment]
Hi,

- The build task is running on a Windows10 with Visual Studio 2019.
- I have a mailaddress in the "To" field and nothing in the "Cc" field. (Tried adding a emailaddress there now - same error).
- There was no part named "Mail Settings" in the output log - the complete output from the task is pasted into the original comment.

I also tried running a different build job now. Same settings, but this one also had an attachment. This one worked as it should :) On this output log, there was a Mail Settings part..

- Maybe it's "missing" the attachment settings...?

**Comment by jpbroeders** [comment]
Hi,

I published a new version to the marketplace, which should fix the problem.
The problem occured when having a Windows Agent without having attachments.

Thanks for reporting :-)
